edition = "2021"
unstable_features = true
wrap_comments = true
imports_granularity = "Module"
group_imports = "StdExternalCrate"
hex_literal_case = "Upper"
format_macro_matchers = true
format_code_in_doc_comments = true
format_strings = true
use_field_init_shorthand = true
use_try_shorthand = true
normalize_comments = true
normalize_doc_attributes = true
overflow_delimited_expr = true